### PR TITLE
Fix tests for Erbium

### PR DESCRIPTION
**Pull request by rory-latchem-imgtec**

### CODE REVIEW

**Comment by seank-img** [comment]
retest this please

**Comment by seank-img** [comment]
@david-antliff-imgtec Do you know why the erbium tools tests is hanging in the CI job? running the tests (not in docker) locally works. I will try the docker tests locally to see if it hangs...

**Comment by seank-img** [comment]
Docker tests run locally with ```DOCKER_RUN_EXTRA_OPTIONS="-e CMAKE_OPTIONS=-DWITH_ERBIUM=ON" bash ci/ci-docker.sh``` completed successfully.

**Comment by meowsqueak** [comment]
@seank-img it could be the '-t' (terminal) flag on docker-run, which needs to be omitted in the Jenkins environment. I'll check it tomorrow. There's logic in the ci/ci-docker.sh script to remove this when no terminal is available, but maybe there's a bug now.

**Comment by david-antliff-imgtec** [comment]
retest this please

**Pull request merged**
