### PR TITLE
gitignore: Ignore generated .cmake

### PR DESCRIPTION
**Pull request by francois-berder-imgtec**
Signed-off-by: Francois Berder <francois.berder@imgtec.com>

### CODE REVIEW

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (erbium)

**Comment by cheekyhalf** [comment]
retest AWS CI (erbium)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (erbium)

**Comment by cheekyhalf** [comment]
retest AWS CI (erbium)

**Comment by boyvinall** [comment]
retest AWS CI (libcoap)

**Pull request merged**
