### PR TITLE
Update travis.yml to use pip's requirements.txt to install Python dependencies

### PR DESCRIPTION
**Pull request by DavidAntliff**
Needed by https://github.com/FlowM2M/AwaLWM2M/pull/324

### CODE REVIEW

**Comment by DavidAntliff** [comment]
@GonZo technically this change won't affect the Jenkins builds, but if you could verify my change and let Jenkins proceed that would be helpful, please. Not sure why I'm no longer whitelisted...

**Comment by GonZo** [comment]
retest AWS CI (erbium)

**Comment by GonZo** [comment]
retest AWS CI (libcoap)

**Comment by GonZo** [comment]
LGTM

**Pull request merged**
