### PR TITLE
Static library build for RIOT

### PR DESCRIPTION
**Pull request by datachi7d**
See https://github.com/datachi7d/RIOT/tree/awa for RIOT build:

```
# git clone https://github.com/datachi7d/RIOT.git --branch awa --depth 1
# cd RIOT
# make -C examples/AwaLWM2M-client/
```

Note: this does not use the RIOT network stack - still work to do there. I didn't have much luck with the RIOT POSIX socket implementation with network_abstraction_linux.c, so possibly network_abstraction_riot.c is needed.

### CODE REVIEW

**Comment by datachi7d** [comment]
retest AWS CI (libcoap)

**Comment by datachi7d** [comment]
retest AWS CI (libcoap)

**Comment by datachi7d** [comment]
retest AWS valgrind (libcoap)

**Comment by boyvinall** [comment]
Hi @datachi7d.  Looks good thanks. Just one thing .. could you sign the commits please?  I'll try to get the DCO check in the check list soon.

**Comment by datachi7d** [comment]
From some more experimentation it seems like using CMake to build in RIOT is a bad idea - it's not really supported at all and is rather hacky. So while these changes are valid I don't recommend using CMake for RIOT, my original idea was to use the Contiki `Makefile.common`, `Makefile.client` and `Makefile.erbium` to build on RIOT. I can post a pull request with the modifications required to build under RIOT using the Contiki makefiles.

**Comment by boyvinall** [comment]
Ok, thanks Sean.  Will probably close this one then I guess.  I see there are some casts in this, which presumably would still apply, but easier to take those in a separate patch. 

FYI, from some discussions we've had internally, we're half-considering re-visiting the overall makefile structure. It's starting to feel like a bunch of separate makefiles for different platforms .. linux, contiki, RIOT, zephyr. As usual, we have a bunch of things ongoing, so the re-visited makefile structure hasn't had a great deal of thought yet, but I thought it worth mentioning. Would be interested to see what you come up with in re-using the contiki makefiles though.

**Pull request closed without merging**
