### PR TITLE
Add support for mbed TLS

### PR DESCRIPTION
**Pull request by delmet**

### CODE REVIEW

**Comment by GonZo** [comment]
retest AWS CI (erbium)

**Comment by GonZo** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by francois-berder-imgtec** [comment]
I am currently having a look at the code, doing some cleanup...

**Comment by boyvinall** [comment]
closing this now, will use changes from @francois-berder-imgtec which have these changes and more

**Pull request closed without merging**
