### PR TITLE
Updated static api examples

### PR DESCRIPTION
**Pull request by TonyWalsworthImg**
Updated static api examples, added supporting images.

### CODE REVIEW

**Comment by seank-img** [comment]
@TonyWalsworthImg the image Awa_client_tutorial_application_positioning_static_api.png is incorrect as there is no client daemon with the Static API, it should look something like:

image

What we need to show is that the client tutorial application is the only process - with the Awa API we have two processes (the example aplication and the client daemon) that communicate over the IPC that represent the client. With the Awa static API we have a single process that handles the application logic and the LWM2M processing, and this represents the client.

**Comment by TonyWalsworthImg** [comment]
I've adjusted the image in line with suggestions. I've also changed the remaining image to remove the client daemon.
awa_client_tutorial_application_positioning_static_api

and...

awa_client_tutorial_static_api

**Comment by david-antliff-imgtec** [comment]
@TonyWalsworthImg looks good, however this needs to be merged with the base branch before we can merge it.

**Comment by TonyWalsworthImg** [comment]
@david-antliff-imgtec I carried out a base branch merge - so should be good to go.

**Pull request merged**
