### PR TITLE
Refactor Core handlers and add error messages for handlers

### PR DESCRIPTION
**Pull request by seank-img**
Signed-off-by: Sean Kelly <Sean.Kelly@imgtec.com>

### CODE REVIEW

**Comment by seank-img** [comment]
@pratik-prajapati-imgtec was returning an incorrect AwaResult for the write handler (https://github.com/pratik-prajapati-imgtec/libobjects-1/commit/5815d542614d8fc71d420dd58af5d74342c60324#commitcomment-16946253) but there was no error message in the core to indicate this.

**Comment by david-antliff-imgtec** [comment]
Is it worth adding some tests now to cover this sort of behaviour?

**Comment by seank-img** [comment]
@david-antliff-imgtec currently the result returned in the handler is not passed through to the coap - so there is no feedback to a server about what kind of error occured in the handler leaving nothing to test. When/If we do this is where tests need to be written. Other than that there is testing the printing of error messages?

**Comment by david-antliff-imgtec** [comment]
If you think it's worth testing for expected error messages, then you can use the CaptureStderr class in the test framework, otherwise if you don't think it's necessary I'm happy to merge this.

**Pull request merged**
