### PR TITLE
Fix Coverity issues 115871 and 115872.

### PR DESCRIPTION
**Pull request by david-antliff-imgtec**
Signed-off-by: David Antliff <david.antliff@imgtec.com>

### CODE REVIEW

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by seank-img** [comment]
[valgrind]

**Comment by seank-img** [comment]
[valgrind]

**Comment by seank-img** [comment]
[valgrind]

**Comment by seank-img** [comment]
[valgrind]

**Comment by seank-img** [comment]
Valgrind is failing due to ghprb on jenkins - https://issues.jenkins-ci.org/browse/JENKINS-35170

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Comment by david-antliff-imgtec** [comment]
[valgrind]

**Pull request merged**
