### PR TITLE
Python 3.6 invalid escape sequence deprecation fixes

### PR DESCRIPTION
**Pull request by scop**
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

### CODE REVIEW

**Comment by boyvinall** [comment]
Hey @scop, thanks for the PR.  This isn't an area I'm too familiar with, and I know there were some previous issues around compatibility between python2 and python3. Do you know if this syntax is valid for python2 also?

**Comment by scop** [comment]
Yes, it is safe to use in both Python 2 and 3.

**Comment by DavidAntliff** [comment]
I don't think the `&` should have been escaped in the first place. There shouldn't be a `\&` in a CoAP URL as far as I can tell. The raw string literal makes `\` be just a normal backslash, but I don't think it's necessary. How about:

```python
result = server_write(self.config, "/3/0/15?pmin=10&pmax=20")
```

**Comment by DavidAntliff** [comment]
However, I'm not sure where that string goes - does it get processed later by a shell? I should have checked that actually, maybe the `\` is required downstream. If so, it might be better to use `\\&` rather than a raw string literal, but either would work.

**Comment by DavidAntliff** [comment]
I removed my earlier comments as I was mistaken - this change looks OK to me, although I'd probably opt for `"\\&"` rather than `r"\&"` - either works.

**Comment by boyvinall** [comment]
Hi @scop, please could you update the PR as per @DavidAntliff's comments above?  Many thanks.

**Comment by scop** [comment]
@boyvinall done.

**Comment by boyvinall** [comment]
retest AWS CI (libcoap)

**Comment by boyvinall** [comment]
retest AWS CI (erbium)

**Comment by boyvinall** [comment]
retest AWS CI (libcoap)

**Pull request merged**
