### PR TITLE
Rework the Contiki network address cache

### PR DESCRIPTION
**Pull request by mtusnio**
@cheekyhalf This uses one of the fixes from your patch, lines 254-257. Otherwise it fails to bootstrap

The whole cache has been reworked to first parse the URI, then compare using Contiki implementation of network addresses. It compares them based on port & IP, and any URI comparison is gone at this point. This should solve the issue with cache overflowing when, for instance, doing observes which pass a slightly different URI to the application.

### CODE REVIEW

**Comment by GonZo** [comment]
retest AWS CI (erbium)

**Comment by cheekyhalf** [comment]
@mtusnio you'll need the other line from the patch otherwise you'll end up with useCount=2 on the first call.

**Comment by mtusnio** [comment]
@cheekyhalf I don't have access to the patch at the moment, can you attach the diff with that line so that I can update the PR?

**Comment by cheekyhalf** [comment]
retest AWS CI (erbium)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Comment by cheekyhalf** [comment]
retest AWS CI (libcoap)

**Pull request merged**
