### PR TITLE
Disable JSON support by default

### PR DESCRIPTION
**Pull request by seank-img**

### CODE REVIEW

**Comment by DavidAntliff** [comment]
Looks good, happy to merge, curious as to whether there's a reason for the change though?

**Comment by seank-img** [comment]
JSON support is more of an optional thing - when do we ever use it day to day? Also it slows down the build ;)

**Comment by cdewbery** [comment]
I guess it's okay to disable it as long as it still gets tested ;)

**Comment by DavidAntliff** [comment]
That would be my only concern really - OK to disable it, but "slowing down the build" probably isn't a valid reason as we'd need to test it anyway, otherwise we might as well take it out completely (and that seems a shame given we do support it).

**Comment by delme-imgtec** [comment]
We are only talking about not having it on by default. Which means one less unneeded dependency and bloat for most situations.

**Pull request merged**
