### PR TITLE
Fix issues highlighted by coverity.com on commit 05879c4.

### PR DESCRIPTION
**Pull request by david-antliff-imgtec**
This patch fixes many issues raised by the Coverity online static analysis tool.

Signed-off-by: David Antliff <david.antliff@imgtec.com>

### CODE REVIEW

**Comment by chris-dewbery-imgtec** [comment]
+1

**Comment by chris-dewbery-imgtec** [comment]
retest this please

**Comment by chris-dewbery-imgtec** [comment]
retest the please

**Comment by david-antliff-imgtec** [comment]
retest this please

**Comment by rolandbewick-img** [comment]
+1

**Comment by david-antliff-imgtec** [comment]
retest this please

**Pull request merged**
