### PR TITLE
Fix reference to IPC documentation

### PR DESCRIPTION
**Pull request by cdewbery**
Signed-off-by: Chris Dewbery <chris.dewbery@gmail.com>

### CODE REVIEW

**Comment by cdewbery** [comment]
add to whitelist

**Comment by datachi7d** [comment]
add to whitelist

**Comment by datachi7d** [comment]
ok to test

**Comment by datachi7d** [comment]
add to whitelist

**Comment by seank-img** [comment]
@cdewbery ghprb was setup so that only @FlowM2MJenkinsCI was an admin, and only admins can white list. I've made everyone in FlowM2M admins.

@boyvinall - this is why your pull request was not building - we should probably add you to the FlowM2M organisation.

**Pull request merged**
