### PR TITLE
Change for older versions of GnuTLS that do not support AES-128-CCM-8

### PR DESCRIPTION
**Pull request by delmet**
Signed-off-by: delmet <delmejt@gmail.com>

### CODE REVIEW

**Comment by delmet** [comment]
retest AWS CI (erbium)

**Comment by DavidAntliff** [comment]
ok to test

**Comment by DavidAntliff** [comment]
test this please

**Comment by DavidAntliff** [comment]
retest AWS CI (erbium)

**Comment by GonZo** [comment]
retest AWS CI (erbium)

**Comment by boyvinall** [comment]
retest AWS CI (libcoap)

**Pull request merged**
