### PR TITLE
Get registration status for static client API

### PR DESCRIPTION
**Pull request by rory-latchem-imgtec**
Add support for static clients to retrieve the current client bootstrap or registration status.
E.g. this allows a client to display 'online' status when registered (needed by creator-wifire-app).

### CODE REVIEW

**Comment by cdewbery** [comment]
retest

**Comment by DavidAntliff** [comment]
retest AWS CI (erbium)

**Comment by DavidAntliff** [comment]
If the AWS CI (erbium) tests don't re-run, it looks like we may still have that GHPRB/Jenkins bug where triggers don't work. Might have to look at updating Jenkins & GHPRB next week.

**Comment by cdewbery** [comment]
Looks good to me.  If you want to get rid of the merge commit you could perform a rebase with origin/master and then force push back to your branch.

**Comment by DavidAntliff** [comment]
Consider adding corresponding tests to keep coverage up. At the least, all API functions should have tests, especially covering null pointer inputs.

**Comment by rory-latchem-imgtec** [comment]
I need this to be accepted so that I can get the final WiFire release done - this uses this new feature. The API entry call DOES check for null already - and returned invalid response.
I will add test coverage after WiFire release is done - it more important to get the feature work finished first

**Comment by DavidAntliff** [comment]
Fair enough :)

**Pull request merged**
