### PR TITLE
Fix awa client explore

### PR DESCRIPTION
**Pull request by francois-berder-imgtec**

### CODE REVIEW

**Comment by GonZo** [comment]
LGTM

**Comment by DavidAntliff** [comment]
Just a note on this - the tools were written in a way to provide "functions" for other tools/programs to use. By combining the Explore functionality into the tool's `main` function, you've removed the function `Explore` from the collection of useful functions, and in my opinion that's a step backwards.

**Comment by GonZo** [comment]
@francois-berder-imgtec can you fix this based on David's comment ?

**Comment by francois-berder-imgtec** [comment]
@DavidAntliff Then why the function ```Explore``` was declared as static ? How could it be called from outside of the file ?
I agree that I could have split my code into small functions.

**Comment by DavidAntliff** [comment]
@francois-berder-imgtec that's a good point, it's not directly usable as-is. However the intention was to separate each function from the main command-line parsing/connection logic, so that people can use those tools as examples to build their own applications. If someone wants to use one of those functions, they can either copy/paste them, or make them non-static and link against them. It's much harder to do this if the functionality is buried amongst the boilerplate.

**Comment by boyvinall** [comment]
Also ... Small, single-purpose functions is always a good idea.  (Except in some ultra-gnarly performance/constrained cases.)

**Comment by francois-berder-imgtec** [comment]
@DavidAntliff Got it. I will refactor my code.

**Pull request merged**
