### PR TITLE
Update CONTRIBUTORS

### PR DESCRIPTION
**Pull request by DavidAntliff**
Removed obsolete email address.

**This is a slightly unusual PR. Please delete the branch after merging.**

### CODE REVIEW

**Comment by DavidAntliff** [comment]
retest AWS CI (erbium)

**Comment by DavidAntliff** [comment]
@seank-img retest trigger isn't working...

**Comment by seank-img** [comment]
retest AWS CI (erbium)

**Comment by seank-img** [comment]
@DavidAntliff  not sure why the trigger didn't work - maybe username change didn't propagate thru to the github REST API?

**Pull request merged**
