### PR TITLE
Fix GNUTLS certificateFormat definition

### PR DESCRIPTION
**Pull request by boyvinall**

### CODE REVIEW

**Comment by delme-imgtec** [comment]
retest

**Comment by DavidAntliff** [comment]
ok to test

**Comment by DavidAntliff** [comment]
add to whitelist

**Comment by DavidAntliff** [comment]
test this please

**Comment by DavidAntliff** [comment]
@seank-img it seems Jenkins isn't responding properly to commands - see Jenkins log: it's noting the commands, but not acting on them.

**Comment by DavidAntliff** [comment]
retest AWS CI (erbium)

**Comment by DavidAntliff** [comment]
retest AWS CI (libcoap)

**Comment by seank-img** [comment]
retest AWS CI (erbium)

**Comment by seank-img** [comment]
I think we are facing this issue - https://issues.jenkins-ci.org/browse/JENKINS-25572

**Pull request closed without merging**
